baseURL = 'https://unitehenry.com/'
languageCode = 'en-us'
title = 'Henry Unite'
theme = 'hugo-bearblog'

[menus]
main = [
  { url = "/certifications", name = "Awards & Certifications", weight = 0 },
  { url = "/game-dev", name = "Game Dev", weight = 1 },
  { url = "https://linkedin.com/in/unitehenry", name = "LinkedIn", weight = 2 },
  { url = "mailto:unitehenry@gmail.com", name = "Email", weight = 3 }
]

[params]
description = "Henry is a Software Engineer in San Francisco"
favicon = "favicon.ico"
hideMadeWithLine = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true
